### ISSUE TITLE
Running out of cuda memory

### ISSUE THREAD

**Issue by fredlumm** [VITA-Group/CADTransformer#3]
Follow the given commands in REAMDE, the code would run successfully, but will soon running out of all cuda memory, it seems the gpu memory is increasing after every few batch.

**Comment by olbod** [comment]
@fredlumm how did you get the data for training?

**Comment by A971RM** [comment]
To get the data is direct. From https://github.com/VITA-Group/CADTransformer/blob/main/preprocess/download_data.py

https://drive.google.com/uc?id=16McNNY_-Y2uVnq42ntZTdYKPWgOZxwp3
https://drive.google.com/uc?id=1xgLqcj91i13_3vhfsUYcRYh3PhFYB9LJ
https://drive.google.com/uc?id=1Hc4-ggsUMoB_5uqJdqYRn9K73QS8rOgG

OR follow README.md
python preprocess/download_data.py  --data_save_dir xx

**Comment by olbod** [comment]
@fredlumm It works for me. Thank you!

**Comment by WHQCHINA** [comment]
> 

data download ,
downloading train...
An error has occurred using proxy: None
HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=16McNNY_-Y2uVnq42ntZTdYKPWgOZxwp3 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 504 Gateway Time-out')))
downloading val...
An error has occurred using proxy: None
HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1xgLqcj91i13_3vhfsUYcRYh3PhFYB9LJ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 504 Gateway Time-out')))
downloading test...
An error has occurred using proxy: None
HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Hc4-ggsUMoB_5uqJdqYRn9K73QS8rOgG (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))

**Comment by WHQCHINA** [comment]
> @fredlumm It works for me. Thank you!

how did you get the data ?

**Comment by zhiwenfan** [comment]
use: python preprocess/download_data.py  --data_save_dir  /ssd1/zhiwen/datasets/svg_raw
